# Generated by Django 4.1.3 on 2022-11-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Chat",
            new_name="Chats",
        ),
        migrations.RenameModel(
            old_name="Room",
            new_name="Rooms",
        ),
    ]
